export {default as Home} from './Home/Home'
export {default as Browse} from './Browse/Browse'
export {default as Login} from './Login/Login'
export {default as Register} from './Register/Register'
export {default as Watch} from './Watch/Watch'