export {default as Navbar } from './Navbar/'
export {default as Banner } from './Banner/Banner'
export {default as Featured } from './Featured/'
export {default as Footer } from './Footer/Footer'
export {default as MovieList } from './MovieList/MovieList'
export {default as Modal } from './Modal/Modal'
